<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.infobip.kafkistry</groupId>
        <artifactId>kafkistry-parent</artifactId>
        <version>0.10.2-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <name>Kafkistry legacy Kafka shaded artifact</name>
    <artifactId>kafkistry-legacy-kafka</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.13</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.13</artifactId>
            <version>${legacy.kafka.version}</version>
            <classifier>test</classifier>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-server</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-server-common</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-storage</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-group-coordinator-api</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-group-coordinator</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-raft</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-transaction-coordinator</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-metadata</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>${zookeeper.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper-jute</artifactId>
            <version>${zookeeper.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
            <version>${legacy-spring-kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
            <version>${legacy-spring-kafka.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                </configuration>
                <executions>
                    <execution>
                        <id>main-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>org.apache.kafka:kafka_2.13</include>
                                    <include>org.apache.kafka:kafka-clients</include>
                                    <include>org.apache.kafka:kafka-server</include>
                                    <include>org.apache.kafka:kafka-server-common</include>
                                    <include>org.apache.kafka:kafka-storage</include>
                                    <include>org.apache.kafka:kafka-group-coordinator-api</include>
                                    <include>org.apache.kafka:kafka-group-coordinator</include>
                                    <include>org.apache.kafka:kafka-transaction-coordinator</include>
                                    <include>org.apache.kafka:kafka-raft</include>
                                    <include>org.apache.kafka:kafka-metadata</include>
                                    <include>org.apache.zookeeper:zookeeper</include>
                                    <include>org.apache.zookeeper:zookeeper-jute</include>
                                    <include>org.springframework.kafka:spring-kafka</include>
                                    <include>org.springframework.kafka:spring-kafka-test</include>
                                </includes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <includes>
                                        <include>com/infobip/kafkistry/**</include>
                                        <include>META-INF/*.kotlin_module</include>
                                        <include>kafka/**</include>
                                        <include>org/apache/kafka/**</include>
                                        <include>org/apache/zookeeper/**</include>
                                        <include>org/springframework/kafka/**</include>
                                    </includes>
                                </filter>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*LICENCE*</exclude>
                                        <exclude>META-INF/*NOTICE*</exclude>
                                        <exclude>META-INF/*DEPENDENCIES*</exclude>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>org/springframework/kafka/annotation/**</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <relocations>
                                <relocation>
                                    <pattern>kafka</pattern>
                                    <shadedPattern>com.infobip.kafkistry.shaded.kafka</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.kafka</pattern>
                                    <shadedPattern>com.infobip.kafkistry.shaded.org.apache.kafka</shadedPattern>
                                    <excludes>
                                        <exclude>org.apache.kafka.common.security.auth.AuthenticateCallbackHandler</exclude>
                                        <exclude>org.apache.kafka.common.security.oauthbearer.OAuthBearerTokenCallback</exclude>
                                        <exclude>org.apache.kafka.common.security.oauthbearer.OAuthBearerToken</exclude>
                                    </excludes>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.zookeeper</pattern>
                                    <shadedPattern>com.infobip.kafkistry.shaded.org.apache.zookeeper</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.springframework.kafka</pattern>
                                    <shadedPattern>com.infobip.kafkistry.shaded.org.springframework.kafka</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
