<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.infobip.kafkistry</groupId>
        <artifactId>kafkistry-parent</artifactId>
        <version>0.10.2-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <name>Kafkistry common utilities</name>
    <artifactId>kafkistry-common</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.infobip.kafkistry</groupId>
            <artifactId>kafkistry-model</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>de.siegmar</groupId>
            <artifactId>logback-gelf</artifactId>
            <version>${logback-gelf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jetty</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons-io.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-properties</artifactId>
        </dependency>

        <!--To include zookeeper and kafka client to be able to work with older ZK based clusters kafka ver 2.x -->
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.13</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.13</artifactId>
            <version>${legacy.kafka.version}</version>
            <classifier>test</classifier>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-server</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-server-common</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-storage</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-group-coordinator-api</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-group-coordinator</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-raft</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-transaction-coordinator</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-metadata</artifactId>
            <version>${legacy.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
            <version>${legacy-spring-kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
            <version>${legacy-spring-kafka.version}</version>
<!--            It should have been test scope, but could not achieve proper class visibility in connector module-->
<!--            <scope>test</scope>-->
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                </configuration>
                <executions>
                    <execution>
                        <id>main-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>org.apache.kafka:kafka_2.13</include>
                                    <include>org.apache.kafka:kafka-clients</include>
                                    <include>org.apache.kafka:kafka-server</include>
                                    <include>org.apache.kafka:kafka-server-common</include>
                                    <include>org.apache.kafka:kafka-storage</include>
                                    <include>org.apache.kafka:kafka-group-coordinator-api</include>
                                    <include>org.apache.kafka:kafka-group-coordinator</include>
                                    <include>org.apache.kafka:kafka-transaction-coordinator</include>
                                    <include>org.apache.kafka:kafka-raft</include>
                                    <include>org.apache.kafka:kafka-metadata</include>
                                    <include>org.apache.zookeeper:zookeeper</include>
                                    <include>org.apache.zookeeper:zookeeper-jute</include>
                                    <include>org.springframework.kafka:spring-kafka</include>
                                    <include>org.springframework.kafka:spring-kafka-test</include>
                                </includes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <includes>
                                        <!-- keep our module stuff -->
                                        <include>com/infobip/kafkistry/**</include>
                                        <include>META-INF/*.kotlin_module</include>

                                        <include>kafka/**</include>
                                        <include>org/apache/kafka/**</include>
                                        <include>org/apache/zookeeper/**</include>
                                        <include>org/springframework/kafka/**</include>
                                    </includes>
                                </filter>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*LICENCE*</exclude>
                                        <exclude>META-INF/*NOTICE*</exclude>
                                        <exclude>META-INF/*DEPENDENCIES*</exclude>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <!-- avoid auto registering stuff (kafka streams gets picked up by spring boot)-->
                                        <exclude>org/springframework/kafka/annotation/**</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <relocations>
                                <relocation>
                                    <pattern>kafka</pattern>
                                    <shadedPattern>com.infobip.kafkistry.shaded.kafka</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.kafka</pattern>
                                    <shadedPattern>com.infobip.kafkistry.shaded.org.apache.kafka</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.zookeeper</pattern>
                                    <shadedPattern>com.infobip.kafkistry.shaded.org.apache.zookeeper</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.springframework.kafka</pattern>
                                    <shadedPattern>com.infobip.kafkistry.shaded.org.springframework.kafka</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
